---
- name: Copy change-doris-root-password.sh to fe-1 node
  ansible.builtin.template:
    src: templates/change-doris-root-password.sh.j2
    dest: "{{ ansible_transfer_dir }}/change-doris-root-password.sh"
    owner: root
    group: root
    mode: '0744'

- name: Excute change-doris-root-password.sh
  ansible.builtin.command: "/usr/bin/sh {{ ansible_transfer_dir }}/change-doris-root-password.sh"
  changed_when: true

- name: Delete change-doris-root-password.sh
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_transfer_dir }}/change-doris-root-password.sh"
