---
- name: Create a directory for ansible to transfer files
  ansible.builtin.file:
    path: "{{ ansible_transfer_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Copy chrony package to remote {{ ansible_transfer_dir }} directory"
  ansible.builtin.copy:
    src: "{{ local_chrony_pkg_path }}"
    dest: "{{ ansible_transfer_dir }}/"
    owner: root
    group: root
    mode: '0755'

- name: Uncompress chrony package
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ ansible_transfer_dir }}/{{ chrony_pkg_name }}"
    dest: "{{ ansible_transfer_dir }}"
    owner: root
    group: root
    mode: '0755'

- name: "Find all rpm package in {{ remote_chrony_pkg_uncompressed_dir }} directory"
  ansible.builtin.find:
    paths: "{{ remote_chrony_pkg_uncompressed_dir }}"
    patterns: "*.rpm"
  register: rpm_files

- name: Set host variable rpm_list
  ansible.builtin.set_fact:
    rpm_list: "{{ rpm_files.files | map(attribute='path') | list }}"

- name: Install chrony
  ansible.builtin.yum:
    name: "{{ rpm_list }}"
    state: present

- name: Copy chronyd configuration
  ansible.builtin.template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Restart chronyd and enable start on boot
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
    enabled: true

- name: "Clean remote temporary directory"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ remote_chrony_pkg_uncompressed_dir }}"
