- name: Create a directory for ansible to transfer files
  ansible.builtin.file:
    path: "{{ ansible_transfer_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy minio client package to remote
  ansible.builtin.copy:
    src: "{{ local_minio_client_pkg_path }}"
    dest: "{{ ansible_transfer_dir }}"
    owner: root
    group: root
    mode: '0755'

- name: Uncompress minio client package
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ ansible_transfer_dir }}/{{ minio_client_pkg_name }}"
    dest: "{{ ansible_transfer_dir }}/"
    owner: root
    group: root
    mode: '0755'

- name: Install minio client mc
  ansible.builtin.copy:
    remote_src: true
    src: "{{ remote_minio_client_uncompressed_dir }}/mc"
    dest: "/usr/bin/mc"
    mode: '0755'

- name: "Clean remote temporary directory"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ remote_minio_client_uncompressed_dir }}"
