---
- name: Create a directory for ansible to transfer files
  ansible.builtin.file:
    path: "{{ ansible_transfer_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy keepalive package to remote
  ansible.builtin.copy:
    src: "{{ local_keepalive_pkg_path }}"
    dest: "{{ ansible_transfer_dir }}"
    owner: root
    group: root
    mode: '0755'

- name: Uncompress keepalive package
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ ansible_transfer_dir }}/{{ keepalive_pkg_name }}"
    dest: "{{ ansible_transfer_dir }}/"
    owner: root
    group: root
    mode: '0755'

- name: "Find all rpm files in {{ remote_keepalive_uncompressed_dir }} folder"
  ansible.builtin.find:
    paths: "{{ remote_keepalive_uncompressed_dir }}"
    patterns: "*.rpm"
  register: rpm_files

- name: Set host variable rpm_list
  ansible.builtin.set_fact:
    rpm_list: "{{ rpm_files.files | map(attribute='path') | list }}"

- name: Install the rpm files
  ansible.builtin.yum:
    name: "{{ rpm_list }}"
    state: present

- name: Start keepalived and enable start on boot
  ansible.builtin.systemd:
    name: keepalived
    state: started
    enabled: true

- name: Copy nginx health check script
  ansible.builtin.template:
    src: templates/check-nginx.sh.j2
    dest: /etc/keepalived/check-nginx.sh
    owner: root
    group: root
    mode: '0744'

- name: Copy keepalived configuration to master node
  ansible.builtin.template:
    src: templates/keepalived-master.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  when: inventory_hostname == "minio-nginx-1"

- name: Copy keepalived configuration to backup node
  ansible.builtin.template:
    src: templates/keepalived-backup.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == "minio-nginx-2"

- name: Restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted

- name: "Clean remote temporary directory"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ remote_keepalive_uncompressed_dir }}"
