---
- name: Disable SELinux
  selinux:
    state: disabled

- name: Check if firewalld was running
  ansible.builtin.command: firewall-cmd --state
  register: firewalld_status
  ignore_errors: true
  changed_when: false

- name: If firewalld is running, stop it
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - firewalld_status.rc == 0
    - firewalld_status.stdout == "running"

- name: Add maximum number of open files configurations to /etc/security/limits.conf
  ansible.builtin.blockinfile:
    path: /etc/security/limits.conf
    block: |
      root soft nofile 65536
      root hard nofile 65536
      * soft nofile 65536
      * hard nofile 65536
    backup: true

- name: Set vm.max_map_count to 2000000 in /etc/sysctl.conf and reload sysctl
  sysctl:
    name: vm.max_map_count
    value: '2000000'
    state: present
    reload: true

- name: "Set timezone to {{ system_timezone }}"
  ansible.builtin.command: timedatectl set-timezone {{ system_timezone }}
  changed_when: true

- name: Remove swap from fstab
  ansible.builtin.lineinfile:
    path: '/etc/fstab'
    regexp: '\sswap\s'
    state: 'absent'
    backup: true

- name: Disable swap
  ansible.builtin.command: swapoff -a
  when:
    - ansible_swaptotal_mb is defined
    - ansible_swaptotal_mb > 0
  changed_when: true
