---
# example:
# ansible-playbook \
#   -e "system_timezone=Asia/Shanghai" \
#   -e "system_distribution=rhel7.9" \
#   -K \
#   playbooks/dolphinscheduler.yml
- name: Deploy dolphinscheduler
  hosts:
    - dolphinscheduler
  vars:
    ansible_remote_tmp: /tmp
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - dolphinscheduler
